config/routes.rb
Yue::Application.routes.draw do
  resources :app_statuses

  resources :templates

  resources :designers

  resources :in_app_types

  resources :photos

  resources :albums

  get "images/index"
  get "images/new"
  get "images/show"
  post "images/create"
  resources :posts

  devise_for :users

  root :to => "designers#index"
  

  match '/avatar', to: 'home#avatar', via: 'get'
  match '/avatar', to: 'home#create', via: 'post'

  resources :posts do
    resources :comments
  end

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

  namespace :api do
    namespace :v1 do
      devise_scope :user do

        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
        
        get "albums" => "album#index"
        post "albums" => "album#index"

        get 'post' => 'post#index', :as => 'post'
        post  'posts' => 'post#index', :as => 'posts'

        get "info" => 'post#info', :as=> 'info'

        post "upload" => 'post#upload', :as => 'upload'

        
        get "test" => 'test#index', :as => 'test'
        post 'test' => 'test#test'
        

      end

      get 'tasks' => 'tasks#index', :as => 'tasks'
      post 'tasks' => 'tasks#create'
      put 'tasks/:id/open' => 'tasks#open', :as => 'open_task'
      put 'tasks/:id/complete' => 'tasks#complete', :as => 'complete_task'
    end
  end
  
  
  

end

app/models/designer.rb
class Designer < ActiveRecord::Base
	 belongs_to :app_status

end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
  before_action :set_designer, only: [:show, :edit, :update, :destroy]

  # GET /designers
  # GET /designers.json
  def index
    @designers = Designer.all
  end

  # GET /designers/1
  # GET /designers/1.json
  def show
  end

  # GET /designers/new
  def new

    @versions = Template.all
    @designer = Designer.new
  end

  # GET /designers/1/edit
  def edit

    @templates = Template.all

  end

  # POST /designers
  # POST /designers.json
  def create
    @designer = Designer.new(designer_params)

    respond_to do |format|
      if @designer.save
        format.html { redirect_to @designer, notice: 'Designer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @designer }
      else
        format.html { render action: 'new' }
        format.json { render json: @designer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designers/1
  # PATCH/PUT /designers/1.json
  def update
    respond_to do |format|
      if @designer.update(designer_params)
        format.html { redirect_to @designer, notice: 'Designer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @designer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designers/1
  # DELETE /designers/1.json
  def destroy
    @designer.destroy
    respond_to do |format|
      format.html { redirect_to designers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_designer
      @designer = Designer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def designer_params
      params.require(:designer).permit(:degn_id, :name, :spell, :template, :app_status_id)
    end
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/views/designers/_form.html.erb
<%= form_for( @designer) do |f| %>
  <% if @designer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@designer.errors.count, "error") %> prohibited this designer from being saved:</h2>

      <ul>
      <% @designer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :degn_id %><br>
    <%= f.text_field :degn_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :spell %><br>
    <%= f.text_field :spell %>
  </div>
  <div class="field">
    <%= f.label :spell %><br>
    <%= f.text_field :spell %>
  </div>
  <div class="field">
    <%= f.label  :app_status_id %><br>
    <%= f.text_field  :app_status_id %>
  
    <%= fields_for :app_status, @designer.app_status do |app_status_fields| %>
      <%= app_status_fields.text_field :name %>  
    <% end %>

  </div>
  <div class="field">
    <%= f.label :template %><br>
    <%= f.text_field :template  %>

  <div class="field">
  参考填写：
    <% @templates.each do |t| %>
      <%= t.spell %>（<%= t.name %>）
      <%= check_box_tag "templates[spell]", t.id %>  

    <% end %>



  </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/designers/edit.html.erb
<h1>Editing designer</h1>

<%= render 'form' %>

<%= link_to 'Show', @designer %> |
<%= link_to 'Back', designers_path %>

app/views/designers/index.html.erb
<h1> designers</h1>

<table>
  <thead>
    <tr>
      <th><%= t(:Degn) %></th>
      <th><%= t(:Name) %></th>
      <th><%= t(:Spell) %></th>
      <th><%= t(:Template) %></th>
      <th><%= t(:app_status_id) %></th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @designers.each do |designer| %>
      <tr>
        <td><%= designer.degn_id %></td>
        <td><%= designer.name %></td>
        <td><%= designer.spell %></td>
        <td><%= designer.template %></td>
        <td><%= designer.app_status_id %></td>

        <td><%= link_to 'Show', designer %></td>
        <td><%= link_to 'Edit', edit_designer_path(designer) %></td>
        <td><%= link_to 'Destroy', designer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Designer', new_designer_path %>

app/views/designers/new.html.erb
<h1>New designer</h1>

<%= render 'form' %>

<%= link_to 'Back', designers_path %>

app/views/designers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Degn:</strong>
  <%= @designer.degn_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @designer.name %>
</p>

<p>
  <strong>Spell:</strong>
  <%= @designer.spell %>
</p>

<p>
  <strong>Template:</strong>
  <%= @designer.template %>
</p>

<%= link_to 'Edit', edit_designer_path(@designer) %> |
<%= link_to 'Back', designers_path %>