config/routes.rb
Yue::Application.routes.draw do
  resources :app_statuses

  resources :templates

  resources :designers

  resources :in_app_types

  resources :photos

  resources :albums

  get "images/index"
  get "images/new"
  get "images/show"
  post "images/create"
  resources :posts

  devise_for :users

  root :to => "designers#index"
  

  match '/avatar', to: 'home#avatar', via: 'get'
  match '/avatar', to: 'home#create', via: 'post'

  resources :posts do
    resources :comments
  end

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

  namespace :api do
    namespace :v1 do
      devise_scope :user do

        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
        
        get "albums" => "album#index"
        post "albums" => "album#index"

        get 'post' => 'post#index', :as => 'post'
        post  'posts' => 'post#index', :as => 'posts'

        get "info" => 'post#info', :as=> 'info'

        post "upload" => 'post#upload', :as => 'upload'

        
        get "test" => 'test#index', :as => 'test'
        post 'test' => 'test#test'
        

      end

      get 'tasks' => 'tasks#index', :as => 'tasks'
      post 'tasks' => 'tasks#create'
      put 'tasks/:id/open' => 'tasks#open', :as => 'open_task'
      put 'tasks/:id/complete' => 'tasks#complete', :as => 'complete_task'
    end
  end
  
  
  

end

app/controllers/in_app_types_controller.rb
class InAppTypesController < ApplicationController
  before_action :set_in_app_type, only: [:show, :edit, :update, :destroy]

  # GET /in_app_types
  # GET /in_app_types.json
  def index
    @in_app_types = InAppType.all
  end

  # GET /in_app_types/1
  # GET /in_app_types/1.json
  def show
  end

  # GET /in_app_types/new
  def new
    @in_app_type = InAppType.new
  end

  # GET /in_app_types/1/edit
  def edit
  end

  # POST /in_app_types
  # POST /in_app_types.json
  def create
    @in_app_type = InAppType.new(in_app_type_params)

    respond_to do |format|
      if @in_app_type.save
        format.html { redirect_to @in_app_type, notice: 'In app type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @in_app_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @in_app_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /in_app_types/1
  # PATCH/PUT /in_app_types/1.json
  def update
    respond_to do |format|
      if @in_app_type.update(in_app_type_params)
        format.html { redirect_to @in_app_type, notice: 'In app type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @in_app_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /in_app_types/1
  # DELETE /in_app_types/1.json
  def destroy
    @in_app_type.destroy
    respond_to do |format|
      format.html { redirect_to in_app_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_in_app_type
      @in_app_type = InAppType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def in_app_type_params
      params.require(:in_app_type).permit(:display_name, :in_app_type, :description, :apple_id, :apple_bundle_id, :apple_type, :price)
    end
end

app/helpers/in_app_types_helper.rb
module InAppTypesHelper
end

app/views/in_app_types/_form.html.erb
<%= form_for(@in_app_type) do |f| %>
  <% if @in_app_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@in_app_type.errors.count, "error") %> prohibited this in_app_type from being saved:</h2>

      <ul>
      <% @in_app_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :display_name %><br>
    <%= f.text_field :display_name %>
  </div>
  <div class="field">
    <%= f.label :in_app_type %><br>
    <%= f.text_field :in_app_type %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :apple_id %><br>
    <%= f.text_field :apple_id %>
  </div>
  <div class="field">
    <%= f.label :apple_bundle_id %><br>
    <%= f.text_field :apple_bundle_id %>
  </div>
  <div class="field">
    <%= f.label :apple_type %><br>
    <%= f.text_field :apple_type %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/in_app_types/edit.html.erb
<h1>Editing in_app_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @in_app_type %> |
<%= link_to 'Back', in_app_types_path %>

app/views/in_app_types/index.html.erb
<h1>Listing in_app_types</h1>

<table>
  <thead>
    <tr>
      <th>Display name</th>
      <th>In app type</th>
      <th>Description</th>
      <th>Apple</th>
      <th>Apple bundle</th>
      <th>Apple type</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @in_app_types.each do |in_app_type| %>
      <tr>
        <td><%= in_app_type.display_name %></td>
        <td><%= in_app_type.in_app_type %></td>
        <td><%= in_app_type.description %></td>
        <td><%= in_app_type.apple_id %></td>
        <td><%= in_app_type.apple_bundle_id %></td>
        <td><%= in_app_type.apple_type %></td>
        <td><%= in_app_type.price %></td>
        <td><%= link_to 'Show', in_app_type %></td>
        <td><%= link_to 'Edit', edit_in_app_type_path(in_app_type) %></td>
        <td><%= link_to 'Destroy', in_app_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New In app type', new_in_app_type_path %>

app/views/in_app_types/new.html.erb
<h1>New in_app_type</h1>

<%= render 'form' %>

<%= link_to 'Back', in_app_types_path %>

app/views/in_app_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Display name:</strong>
  <%= @in_app_type.display_name %>
</p>

<p>
  <strong>In app type:</strong>
  <%= @in_app_type.in_app_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @in_app_type.description %>
</p>

<p>
  <strong>Apple:</strong>
  <%= @in_app_type.apple_id %>
</p>

<p>
  <strong>Apple bundle:</strong>
  <%= @in_app_type.apple_bundle_id %>
</p>

<p>
  <strong>Apple type:</strong>
  <%= @in_app_type.apple_type %>
</p>

<p>
  <strong>Price:</strong>
  <%= @in_app_type.price %>
</p>

<%= link_to 'Edit', edit_in_app_type_path(@in_app_type) %> |
<%= link_to 'Back', in_app_types_path %>