config/routes.rb
Yue::Application.routes.draw do
  resources :app_statuses

  resources :templates

  resources :designers

  resources :in_app_types

  resources :photos

  resources :albums

  get "images/index"
  get "images/new"
  get "images/show"
  post "images/create"
  resources :posts

  devise_for :users

  root :to => "designers#index"
  

  match '/avatar', to: 'home#avatar', via: 'get'
  match '/avatar', to: 'home#create', via: 'post'

  resources :posts do
    resources :comments
  end

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

  namespace :api do
    namespace :v1 do
      devise_scope :user do

        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
        
        get "albums" => "album#index"
        post "albums" => "album#index"

        get 'post' => 'post#index', :as => 'post'
        post  'posts' => 'post#index', :as => 'posts'

        get "info" => 'post#info', :as=> 'info'

        post "upload" => 'post#upload', :as => 'upload'

        
        get "test" => 'test#index', :as => 'test'
        post 'test' => 'test#test'
        

      end

      get 'tasks' => 'tasks#index', :as => 'tasks'
      post 'tasks' => 'tasks#create'
      put 'tasks/:id/open' => 'tasks#open', :as => 'open_task'
      put 'tasks/:id/complete' => 'tasks#complete', :as => 'complete_task'
    end
  end
  
  
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments


  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :skills, :interests


  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
          :default_url => "/images/:style/missing.png", :size => { :in => 0..1800.kilobytes }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


  validates :title, :presence => true, length: { minimum: 5 },
  										:uniqueness => true
  validates :text, :presence => true
	
  
  scope :tag_with, lambda{|tag_name| joins(:tags).where("tags.name = ?", tag_name)}
  scope :latter_than, lambda{|time| joins(:taggings).where("taggings.created_at > ?", time)}



  WillPaginate.per_page = 5



  def description_markdown
    avatar_url  = avatar.url
  end

  def as_json(options)
    super(:only => [:title, :text, :avatar_url], :methods => :description_markdown )
  end




end

app/controllers/api/v1/post_controller.rb
class Api::V1::PostController < ApplicationController

	skip_before_filter :verify_authenticity_token,
										 :if => Proc.new { |c| c.request.format == 'application/json' }
	respond_to :json
	WillPaginate.per_page = 10



	def index
		@posts =  current_user.posts.paginate(:page => params[:page])
	
		render :status => :unprocessable_entity,
						:json => { :success => true,
										 :info => "",
										 :data => @posts}
	end

	def info
		user=User.find_by_authentication_token(params[:auth_token])
		if user
			@posts =  user.posts.paginate(:page => params[:page]).order('created_at DESC')
			render :status => :unprocessable_entity,
			:json => { :success => true,
							 :info => user,
							 :data => @posts }
		else 
			render :status => :unprocessable_entity,
			:json => { :success => false,
							 :info =>"上传要求：jpg ",
							 :data => {} }      
		end 
	end

	def upload
		@image = params[:image]
		render :status => :unprocessable_entity,
					 :json => { :success => false,
										 :info =>" @task.errors.full_messages",
										 :data => {} }
	end 

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index


    
    if signed_in?
      @posts = Post.all  
    else
      redirect_to new_user_session_path
    end

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :text, :user_id, :avatar)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post , :html => {:multipart => true}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>

        <td><%= image_tag post.avatar.url(:thumb) %></td>

        <td><%= post.title %></td>
        <td><%= post.text %></td>
        <td><%= post.user_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
 <%= image_tag @post.avatar.url %>


<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>
 
<h2>Comments</h2>
<%= render @post.comments %>
 
<h2>Add a comment:</h2>
<%= render "comments/form" %>
 
<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %>