config/routes.rb
Yue::Application.routes.draw do
  resources :app_statuses

  resources :templates

  resources :designers

  resources :in_app_types

  resources :photos

  resources :albums

  get "images/index"
  get "images/new"
  get "images/show"
  post "images/create"
  resources :posts

  devise_for :users

  root :to => "designers#index"
  

  match '/avatar', to: 'home#avatar', via: 'get'
  match '/avatar', to: 'home#create', via: 'post'

  resources :posts do
    resources :comments
  end

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

  namespace :api do
    namespace :v1 do
      devise_scope :user do

        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
        
        get "albums" => "album#index"
        post "albums" => "album#index"

        get 'post' => 'post#index', :as => 'post'
        post  'posts' => 'post#index', :as => 'posts'

        get "info" => 'post#info', :as=> 'info'

        post "upload" => 'post#upload', :as => 'upload'

        
        get "test" => 'test#index', :as => 'test'
        post 'test' => 'test#test'
        

      end

      get 'tasks' => 'tasks#index', :as => 'tasks'
      post 'tasks' => 'tasks#create'
      put 'tasks/:id/open' => 'tasks#open', :as => 'open_task'
      put 'tasks/:id/complete' => 'tasks#complete', :as => 'complete_task'
    end
  end
  
  
  

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :photos

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


  def avatar_url
    avatar_url  = avatar.url
  end

  def as_json(options)
    super(:only => [:title, :text, :avatar_url, :updated_at], :methods => :avatar_url )
  end
end

app/models/app_status.rb
class AppStatus < ActiveRecord::Base
  has_many :designer

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :body, presence: true,
                    length: { minimum: 5 }

                    
end

app/models/designer.rb
class Designer < ActiveRecord::Base
	 belongs_to :app_status

end

app/models/in_app_type.rb
class InAppType < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/



end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments


  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :skills, :interests


  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
          :default_url => "/images/:style/missing.png", :size => { :in => 0..1800.kilobytes }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


  validates :title, :presence => true, length: { minimum: 5 },
  										:uniqueness => true
  validates :text, :presence => true
	
  
  scope :tag_with, lambda{|tag_name| joins(:tags).where("tags.name = ?", tag_name)}
  scope :latter_than, lambda{|time| joins(:taggings).where("taggings.created_at > ?", time)}



  WillPaginate.per_page = 5



  def description_markdown
    avatar_url  = avatar.url
  end

  def as_json(options)
    super(:only => [:title, :text, :avatar_url], :methods => :description_markdown )
  end




end

app/models/template.rb
class Template < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  STATE = {
    # 软删除
    :deleted => -1,
    # 正常
    :normal => 1,
    # 屏蔽
    :blocked => 2,
  }



  
  has_many :posts
  has_many :albums

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         

   def skip_confirmation!
     self.confirmed_at = Time.now
   end       
   


   def get_user_for(token)
   	 
   	 user = User.find_by_authentication_token(token)
   	 if user
   	 	reture true
   	 end
   	 false


   end
   
   def reset_authentication_token!
   	 self.authentication_token = Digest::MD5::hexdigest(Array.new(10){rand(1024).to_s(36)}.join+DateTime.now.to_s())
   	 self.save()
   end 


	def user_params
	  params.require(:user).permit(:avatar, :email, :password)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index 
    logger.info(current_user)
  end

  def create 


  	current_user.avatar = params[:avatar]
  	current_user.save

  	render 'avatar'
  end


  def avatar

    @user = current_user



    
  end

end

app/helpers/ablums_helper.rb
module AblumsHelper
end

app/helpers/app_statuses_helper.rb
module AppStatusesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Plan App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end


  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/in_app_types_helper.rb
module InAppTypesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/layouts/_footer.html.erb
<br />

<footer>
  <p class="pull-right"><%= link_to "关于我们",   about_path %></p>

</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
	        <ul class="nav navbar-nav navbar">
	          <li><%= link_to image_tag("logo-18.png", alt: "Rails"), 'http://rubyonrails.org/'%>  </li>
	          <li>	<%= link_to t(:site_name), root_path , class:'navbar-brand' %></li>
     
	        </ul>
        </div>
<!-- 

	<li><%= link_to "我的post", posts_path %></li>
			 

  <li><%= link_to "我的post", designers_path %></li>

	<li><%= link_to "我的ablum", albums_path %></li>


	<li><%= link_to "我的photo", photos_path %></li> -->
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

           <li><%= link_to t(:designers), designers_path %></li>
           <li><%= link_to t(:templates), templates_path %></li>
           <li><%= link_to t(:app_statuses), app_statuses_path %></li>

          </ul>
          <ul class="nav navbar-nav navbar-right">

	       

          </ul>
        </div><!--/.nav-collapse -->
      </div>
</div>
<br />

		
	

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>  
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>


    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
      <%= render 'layouts/header' %>
      		<% flash.each do |key, value| %>
        		<div class="alert alert-<%= key %>"><%= value %></div>
      		<% end %>
		<div class="container">
			<%= yield %>
			
			
      <%= render 'layouts/footer' %>
			
      <%= debug(params) if Rails.env.development? %>
		</div>

    </div>
  </body>
</html>

app/views/templates/_form.html.erb
<%= form_for(@template) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :spell %><br>
    <%= f.text_field :spell %>
  </div>
  <div class="field">
    <%= f.label :version %><br>
    <%= f.text_field :version %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<h1>Editing template</h1>

<%= render 'form' %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<h1>Listing templates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Spell</th>
      <th>Version</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @templates.each do |template| %>
      <tr>
        <td><%= template.name %></td>
        <td><%= template.spell %></td>
        <td><%= template.version %></td>
        <td><%= template.status %></td>
        <td><%= link_to 'Show', template %></td>
        <td><%= link_to 'Edit', edit_template_path(template) %></td>
        <td><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Template', new_template_path %>

app/views/templates/new.html.erb
<h1>New template</h1>

<%= render 'form' %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @template.name %>
</p>

<p>
  <strong>Spell:</strong>
  <%= @template.spell %>
</p>

<p>
  <strong>Version:</strong>
  <%= @template.version %>
</p>

<p>
  <strong>Status:</strong>
  <%= @template.status %>
</p>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>